import type { LayoutType, SlideContent, TableColumn, IconGridItem, TeamMember, PinterestPin } from "@/types/slide";

export const SLIDE_DEFAULTS: Record<LayoutType, SlideContent> = {
  cover: {
    eyebrow: "PITCH DECK · 2026",
    headline: "YOUR PROJECT TITLE",
    subheadline: "One line that captures the project's purpose and impact.",
    client_name: "CLIENT NAME",
    deck_type_label: "PITCH DECK",
    background_image_url: "",
    show_logo: true,
  },
  section_divider: {
    section_number: "01",
    section_title: "SECTION TITLE",
    section_subtitle: "",
    background_color: "black",
  },
  stats: {
    headline: "BY THE NUMBERS",
    stats: [
      { value: "—", label: "METRIC ONE", window_title: "STAT.EXE" },
      { value: "—", label: "METRIC TWO", window_title: "STAT.EXE" },
      { value: "—", label: "METRIC THREE", window_title: "STAT.EXE" },
    ],
    columns: 3,
  },
  text_image: {
    eyebrow: "OVERVIEW",
    headline: "HEADLINE GOES HERE",
    body: "Supporting body copy that explains the context, the problem we solved, or the opportunity we captured.",
    image_url: "",
    image_alt: "Project image",
    image_side: "right",
    image_caption: "",
  },
  full_bleed_image: {
    image_url: "",
    image_alt: "Full bleed image",
    overlay_opacity: 55,
    headline: "IMAGE HEADLINE",
    subtext: "",
    text_position: "bottom-left",
    show_scan_lines: false,
  },
  content_list: {
    eyebrow: "KEY POINTS",
    headline: "WHAT WE DELIVERED",
    items: [
      { text: "First key point or deliverable", highlight: false },
      { text: "Second key point or deliverable", highlight: false },
      { text: "Third key point or deliverable", highlight: true },
    ],
    layout: "single-column",
    show_numbers: false,
  },
  quote: {
    quote_text: "The quote or key callout goes here. Keep it short and punchy.",
    attribution: "— Name, Title, Company",
    context: "",
    background_color: "blue",
    show_quotation_mark: true,
  },
  timeline: {
    headline: "PROJECT TIMELINE",
    events: [
      { date: "PHASE 1", title: "Discovery & Planning", description: "", is_milestone: false },
      { date: "PHASE 2", title: "Development", description: "", is_milestone: false },
      { date: "PHASE 3", title: "Launch", description: "", is_milestone: true },
    ],
    orientation: "horizontal",
  },
  thank_you: {
    headline: "LET'S BUILD SOMETHING.",
    subheadline: "We're ready when you are.",
    contact_name: "Your Name",
    contact_title: "Creative Director",
    contact_email: "hello@weareedt.com",
    contact_phone: "",
    website: "weareedt.com",
    show_logo: true,
    background_color: "black",
  },
  table: {
    headline: "COST ESTIMATE",
    eyebrow: "BUDGET BREAKDOWN",
    columns: [
      { key: "id",    label: "#",         width: 6,  align: "center", format: "text"     },
      { key: "item",  label: "Item",       width: 46, align: "left",   format: "text"     },
      { key: "qty",   label: "Qty",        width: 12, align: "center", format: "number"   },
      { key: "cost",  label: "Unit Cost",  width: 18, align: "right",  format: "currency" },
      { key: "total", label: "Total",      width: 18, align: "right",  format: "currency" },
    ] as TableColumn[],
    rows: [
      { id: "01", item: "Design & Creative Direction", qty: 1,  cost: 5000, total: 5000 },
      { id: "02", item: "Development",                 qty: 1,  cost: 8000, total: 8000 },
      { id: "03", item: "Content Production",          qty: 3,  cost: 1200, total: 3600 },
      { id: "04", item: "Project Management",          qty: 1,  cost: 2000, total: 2000 },
    ],
    show_total_row: true,
    total_column: "total",
    currency_symbol: "$",
    highlight_last_column: true,
  },
  chart: {
    headline: "PERFORMANCE OVERVIEW",
    eyebrow: "BY THE NUMBERS",
    chart_type: "bar",
    data: [
      { label: "Q1", value: 42 },
      { label: "Q2", value: 67 },
      { label: "Q3", value: 58 },
      { label: "Q4", value: 91 },
    ],
    value_prefix: "",
    value_suffix: "%",
    series_label: "Value",
    show_legend: false,
    show_values: true,
    show_grid: true,
  },
  video: {
    headline: "",
    video_url: "",
    caption: "",
    autoplay: false,
    show_controls: true,
    background_color: "black",
  },
  image_gallery: {
    headline: "",
    eyebrow: "",
    images: [],
    mode: "tiled",
    tiled_layout: "2x2",
    show_captions: false,
    background_color: "black",
  },
  hero_impact: {
    headline: "MAKE IT\nHAPPEN.",
    headline_size: "xxl",
    subtext: "",
    background_image_url: "",
    overlay_opacity: 55,
    text_alignment: "left",
    accent_bar: true,
    show_logo: false,
  },
  big_number: {
    eyebrow: "KEY METRIC",
    number: "96%",
    label: "METRIC DESCRIPTION",
    context: "",
    background_image_url: "",
    overlay_opacity: 70,
    accent_color: "blue",
  },
  icon_grid: {
    eyebrow: "WHAT WE DO",
    headline: "CAPABILITIES",
    items: [
      { icon: "🎯", label: "STRATEGY", description: "Define the vision" },
      { icon: "🎨", label: "DESIGN", description: "Craft the experience" },
      { icon: "⚡", label: "TECHNOLOGY", description: "Build the future" },
      { icon: "📊", label: "ANALYTICS", description: "Measure impact" },
    ] as IconGridItem[],
    columns: 4,
    style: "cards",
    background_color: "black",
  },
  comparison: {
    headline: "",
    eyebrow: "COMPARISON",
    left_label: "BEFORE",
    left_image_url: "",
    left_image_alt: "Before image",
    left_points: [],
    right_label: "AFTER",
    right_image_url: "",
    right_image_alt: "After image",
    right_points: [],
    divider_style: "line",
  },
  team: {
    eyebrow: "THE TEAM",
    headline: "WHO WE ARE",
    members: [
      { name: "Team Member", title: "Role", image_url: "", image_alt: "Team member photo" },
      { name: "Team Member", title: "Role", image_url: "", image_alt: "Team member photo" },
      { name: "Team Member", title: "Role", image_url: "", image_alt: "Team member photo" },
    ] as TeamMember[],
    layout: "row",
    show_window_chrome: true,
  },
  pinterest_inspo: {
    headline: "INSPIRATION",
    eyebrow: "MOOD BOARD",
    board_url: "",
    pins: [] as PinterestPin[],
    background_color: "black",
  },
};
